---
- name: Setup GitHub Runner
  include_tasks: setup.yml
  when: github_runner_state == "present"

- name: Teardown GitHub Runner
  include_tasks: teardown.yml
  when: github_runner_state == "absent"
