---
- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true
  become: true

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Get PostgreSQL version
  command: psql --version
  register: pg_version_output
  changed_when: false

- name: Set pg_version variable
  set_fact:
    pg_version: "{{ pg_version_output.stdout | regex_search('\\d+') }}"

- name: Configure PostgreSQL to listen on all interfaces
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
  become: true
  notify: restart postgresql

- name: Allow remote connections in pg_hba.conf
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    regexp: '^host\s+{{ tf_db_name | regex_escape }}\s+{{ tf_db_user | regex_escape }}'
    line: "host    {{ tf_db_name }}    {{ tf_db_user }}    0.0.0.0/0    scram-sha-256"
  become: true
  notify: restart postgresql

- name: Allow PostgreSQL traffic in UFW
  ufw:
    rule: allow
    port: '{{ tf_db_port | default(5432) }}'
    proto: tcp
  become: true
  when: ufw_enabled | default(true)

- name: Force PostgreSQL restart to apply all changes
  service:
    name: postgresql
    state: restarted
  become: true

- name: Create {{ tf_db_user }} database user
  postgresql_user:
    name: "{{ tf_db_user }}"
    password: "{{ tf_db_password }}"
    role_attr_flags: "CREATEDB"
  become: true
  become_user: postgres

- name: Create {{ tf_db_name }} database
  postgresql_db:
    name: "{{ tf_db_name }}"
    owner: "{{ tf_db_user }}"
  become: true
  become_user: postgres

- name: Grant connect privilege to {{ tf_db_user }} user
  postgresql_privs:
    db: "{{ tf_db_name }}"
    role: "{{ tf_db_user }}"
    privs: CONNECT
    type: database
  become: true
  become_user: postgres

- name: Create terraform schema
  postgresql_schema:
    db: "{{ tf_db_name }}"
    name: "{{ tf_db_schema }}"
    owner: "{{ tf_db_user }}"
  become: true
  become_user: postgres
