---
# Global Versions
github_runner_version: "2.316.1"
common_node_version: "20"
docker_ubuntu_codename: "noble"

# Security Settings
common_ufw_enabled: true
postgresql_ufw_enabled: true

# GitHub Runner Configuration
github_account_type: "org"
github_org: "NerdIT-Tech"
github_pat: "{{ lookup('env', 'GH_PAT') }}" # Example of getting from env

# Docker & Podman Configuration
docker_users:
  - runner
podman_registries:
  - docker.io
  - quay.io

# PostgreSQL Configuration (Overrides)
# postgresql_db_user: "..."
# postgresql_db_pass: "..."
# postgresql_db_name: "..."

# System Tuning
common_sysctl_settings:
  fs.file-max: 2097152
  net.core.somaxconn: 1024
  vm.swappiness: 10
