---
- name: Add Docker's official GPG key
  get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }} {{ docker_ubuntu_codename }} stable"
    state: present
    filename: docker
  become: true

- name: Install Docker Engine
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: true

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: true
  loop: "{{ docker_users }}"
